apiVersion: apps/v1
kind: Deployment
metadata:
  name: se-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starexec
  template:
    metadata:
      labels:
        app: starexec
    spec:
      nodeSelector:
        nodegroup: headnode
        
      serviceAccountName: starexec-headnode
      initContainers:
      - name: init-volume
        image: tptpstarexec/starexec:latest
        command:
          - sh
          - -c
          - >
            if [ "$(ls -A /mnt/vol-db)" ]; then echo "vol-db is not empty"; else cp -r /var/lib/mysql/* /mnt/vol-db/; fi &&
            if [ "$(ls -A /mnt/vol-star)" ]; then echo "vol-star is not empty"; else cp -r /home/starexec/* /mnt/vol-star/; fi &&
            if [ "$(ls -A /mnt/vol-pro)" ]; then echo "vol-pro is not empty"; else cp -r /project/* /mnt/vol-pro/; fi &&
            chown -R root:root /mnt/vol-db /mnt/vol-star /mnt/vol-pro
        volumeMounts:
        - name: vol-db
          mountPath: /mnt/vol-db
        - name: vol-star
          mountPath: /mnt/vol-star
        - name: vol-pro
          mountPath: /mnt/vol-pro
        # - name: vol-export
        #   mountPath: /mnt/vol-export
      containers:
      - name: starexec
        image: ghcr.io/starexecmiami/starexec-arc:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: vol-db
          mountPath: /var/lib/mysql
        - name: vol-star
          mountPath: /home/starexec
        - name: vol-pro
          mountPath: /project
        # - name: vol-export
        #   mountPath: /export
        - name: ssh-key
          mountPath: /root/.ssh/starexec_podman_key
          # subPath: starexec_podman_key
      volumes:
        - name: vol-db
          persistentVolumeClaim:
            claimName: voldb
        - name: vol-star
          persistentVolumeClaim:
            claimName: volstar
        - name: vol-pro
          persistentVolumeClaim:
            claimName: volpro
        # - name: vol-export
        #   persistentVolumeClaim:
        #     claimName: volexport
        - name: ssh-key
          secret:
            secretName: starexec-ssh-key
