#------------------------------------------------------------
#----To build: podman build --no-cache -t drodi:3.6.0 .
FROM ubuntu-arc

#----Add binary
ADD drodi /artifacts/
ADD drodi.lrn /artifacts/

#----Add run_system script 
ADD run_system /artifacts/

#------------------------------------------------------------
