name: Deploy to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: starexec-terraform
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy StarExec to AWS
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 60

    env:
      AWS_REGION: us-east-1
      DOMAIN: ${{ secrets.DOMAIN != '' && secrets.DOMAIN || 'starexec-arc.net' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cache Terraform plugins and modules
        uses: actions/cache@v3
        with:
          path: |
              ~/.terraform.d/plugin-cache
              starexec-kubernetes/terraform/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
              ${{ runner.os }}-terraform-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make jq

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: make init
        working-directory: starexec-kubernetes/terraform

      - name: Validate Terraform configuration
        run: make validate
        working-directory: starexec-kubernetes/terraform

      - name: Configure AWS CLI region
        run: aws configure set region $AWS_REGION
        working-directory: starexec-kubernetes/terraform
      - name: Plan Terraform changes
        run: |
          if ! timeout 300 make plan; then
            echo "Plan failed or timed out, attempting to force unlock..."
            terraform force-unlock -force $(terraform state list 2>/dev/null | head -1 | cut -d. -f1 2>/dev/null || echo "auto-unlock") || true
            echo "Retrying plan after unlock attempt..."
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
          DOMAIN: ${{ env.DOMAIN }}
        working-directory: starexec-kubernetes/terraform

      - name: Deploy infrastructure
        run: |
          if ! timeout 600 make default; then
            echo "Deploy failed or timed out, attempting to force unlock..."
            terraform force-unlock -force $(terraform state list 2>/dev/null | head -1 | cut -d. -f1 2>/dev/null || echo "auto-unlock") || true
            echo "Retrying deploy after unlock attempt..."
            make default
          fi
        working-directory: starexec-kubernetes/terraform
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}

      - name: Deploy infrastructure
        run: make default
        working-directory: starexec-kubernetes/terraform

      - name: Show cluster information
        run: make info
        working-directory: starexec-kubernetes/terraform

      - name: Notify deployment success
        if: success()
        run: echo "Deployment completed successfully!"

      - name: Notify deployment failure
        if: failure()
        run: echo "Deployment failed. Please check the logs."