name: Deploy to AWS

on:
  push:
    branches:
      - masster
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy StarExec to AWS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1 # Update this to your desired AWS region

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make jq

      - name: Initialize Terraform
        run: make init
        working-directory: starexec-kubernetes/terraform

      - name: Validate Terraform configuration
        run: make validate
        working-directory: starexec-kubernetes/terraform

      - name: Plan Terraform changes
        run: make plan
        working-directory: starexec-kubernetes/terraform

      - name: Deploy infrastructure
        run: make default
        working-directory: starexec-kubernetes/terraform

      - name: Show cluster information
        run: make info
        working-directory: starexec-kubernetes/terraform