name: Infrastructure CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'starexec-kubernetes/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'starexec-kubernetes/**'

env:
  WORKDIR: starexec-kubernetes

jobs:
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}/terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Validate Results
        if: steps.fmt.outcome == 'failure' || steps.init.outcome == 'failure' || steps.validate.outcome == 'failure'
        run: |
          echo "Terraform validation failed."
          echo "Format check outcome: ${{ steps.fmt.outcome }}"
          echo "Init outcome: ${{ steps.init.outcome }}"
          echo "Validate outcome: ${{ steps.validate.outcome }}"
          exit 1

  validate-kubernetes:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Validate Kubernetes manifests
        run: |
          find microk8s/YAMLFiles terraform/YAMLFiles -type f \( -name "*.yaml" -o -name "*.yml" \) -print -exec kubectl apply --dry-run=client -f {} \;